### ISSUE TITLE
All debug UI open at the same time

### ISSUE THREAD

**Issue by KingoRodriguo** [Project-Zomboid-Community-Modding/pz-community-modding#77]
Some time, on save loading, all debug UI open themself at the same time and dont close themself after. 
Tried to search the cause, idk

[console.txt](https://github.com/user-attachments/files/16392206/console.txt)

**Comment by Chuckleberry-Finn** [comment]
It can happen if you close all of the windows - it's an issue with the UI layout saving feature.

**Comment by KingoRodriguo** [comment]
Duplicate of #33
