### ISSUE TITLE
Add proper explanation of functionalities in the various inner readme.md

### ISSUE THREAD

**Issue by theCrius** [Project-Zomboid-Community-Modding/pz-community-modding#78]
`Contents/mods/!pz_debugTools/README.md` should explain which modding tools are included and how to use them
`Contents/mods/!pz_frameworks/README.md` should explain what the framework new features are. Potentially each function should have detailed guides on how to use them with only a generic overview (what does what)
`Contents/mods/!pz_patch/README.md` should list the changes/fix included so that users/modders know what they get

**Comment by Chuckleberry-Finn** [comment]
Fxied with:
12002aab8d3ee78918d9728804f154850585bb25 
c91f2994c558402bc0405d39311171d6cf993ddc
289f01497ed287d48f32e528d395ad8dca9bda4a
